# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harringa.com
description: >
  Generally used as a playground for Justin Harringa but also includes
  blog posts. Of course, all of that is subject to change.
baseurl: ""
url: "https://harringa.com"
social_username: justinharringa
social_networks:
- name: GitHub
  uri: github.com
- name: LinkedIn
  uri: www.linkedin.com/in
- name: Twitter
  uri: twitter.com
permalink: /posts/:year/:month/:day/:title/
exclude: [Gemfile, Gemfile.lock, gulpfile.js, LICENSE, node_modules, package.json, Rakefile, README.md, s3_website.yml, vendor]
author:
  name: "Justin Harringa"

maps:
  google:
    api_key: AIzaSyC7CdiDDoEfq6B-VK1Zbi8bwq6fDkakC1A
# Build settings
markdown: kramdown

plugins: 
  - jekyll-feed
  - jekyll-maps
